### ISSUE TITLE
Set taskname throws error if spaces in task name surrounded by double quotes

### ISSUE THREAD

**Issue by mikeclemson** [Asymmetric-InfoSec/Power-Response#355]
In Persistence\Retrieve-ScheduledTasks, performing **set taskname "Example Task With Spaces"** throws a warning:
`WARNING: Unkown command 'set', 'help' prints a list of available commands`

With verbose logging, PowerShell shows:
`VERBOSE: Illegal characters in path.`

This works correctly if single quotes are used:
**set taskname 'Example Task With Spaces'**

**Comment by 5ynax** [comment]
This bug is no longer an issue in the current release since we removed targeted scheduled task retrieval. This decision was made to reduce the burden on endpoints for multiple task retrievals and since the retrieval of one scheduled task would likely have a similar resource requirement than all scheduled tasks.
