### ISSUE TITLE
Admin Credentials Used for Plugins

### ISSUE THREAD

**Issue by 5ynax** [Asymmetric-InfoSec/Power-Response#6]
@valrkey @5k33tz : Most of plugins in the framework will rely on the user having some sort of administrator credentials that are used to obtain data on remote machines. Are we going to rely on the user running the framework in the context of an admin or should we implement a method to allow the user to run the framework in the standard user context but supply the necessary admin credentials to run plugins necessary?

**Comment by valrkey** [comment]
@5ynax @5k33tz  : Logic for getting the best of both wouldn't be too bad:
1. Default configuration item `UserName` to the current running user if nothing is passed
2. In top section of `Power-Response.ps1`, check if `$ENV:UserName -ne $Config.Authentication.UserName`
  a. If true, prompt for credentials

What that should turn out to be in practice:
Case 1 - User doesn't specify a `Authentication.UserName` configuration line
Result 1 - User will never be prompted for credentials, and it is on them to run as admin

Case 2 - User specifies a `Authentication.UserName` configuration line, and runs as admin
Result 2 - User won't be prompted for authentication since they're (probably) running as the admin account specified in config

Case 3 - User specifies a `Authentication.UserName` configuration line, and runs as loser user
Result 3 - User will be prompted for administrative credentials to be stored once in a `script` level scope that can be passed to any plugins that require elevated privs

If you guys think that's dumb and people should just run as admin we can scrap the `UserName` config variable too, I'm not married to the idea
